//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLVIII_Dejan_Prodanovic.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PizzeriaDatBEntities1 : DbContext
    {
        public PizzeriaDatBEntities1()
            : base("name=PizzeriaDatBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblOrder> tblOrders { get; set; }
        public virtual DbSet<tblPizza> tblPizzas { get; set; }
        public virtual DbSet<tblPizzaOrder> tblPizzaOrders { get; set; }
    }
}
